In [1]:
import pyttsx3
import speech_recognition as sr
import pandas as pd

In [2]:
df = pd.read_csv('Ecommerce Customers.csv')

In [3]:
class VoiceAssistant:
    def __init__(self, df):
        self.df = df
        self.engine = pyttsx3.init()
        self.engine.setProperty('voice', 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0')
        
    def _transform(self):
        r = sr.Recognizer()
        with sr.Microphone() as source:
            print("I am listening...")
            r.energy_threshold = 4000
            r.adjust_for_ambient_noise(source,duration=0.1)
            r.pause_threshold = 0.5
            said = r.listen(source)

            try:
                q = r.recognize_google(said, language='en-US')
                return q

            except sr.UnknownValueError:
                print('Sorry I did not understand')
                return 'I am waiting'

            except sr.RequestError:
                print('Sorry the server is down')
                return 'I am waiting'

            except:
                return "I am waiting"
            
    def _speaking(self, message):
        self.engine.say(message)
        self.engine.runAndWait()
        
    def _whatsup(self):
        self._speaking('''Hi, my name is Zira. I am your personal assistant.
                    How may I help you?''')
        
    def querying(self):
        self._whatsup()

        while True:
            q = self._transform().lower()

            if 'entire data' in q:
                display(self.df)
                continue
            
            elif 'describe' in q:
                display(self.df.describe(include='all'))
                continue
                
            elif 'show' in q or 'features' in q:
                print(list(self.df.columns))
                continue

            elif 'shut' in q or 'down' in q:
                self._speaking('Ok. I am shutting down')
                break

In [4]:
va = VoiceAssistant(df)
va.querying()

I am listening...

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...,...
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642

I am listening...

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
count,500,500,500,500.000000,500.000000,500.000000,500.000000,500.000000
unique,500,500,138,NaN,NaN,NaN,NaN,NaN
top,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",SlateBlue,NaN,NaN,NaN,NaN,NaN
freq,1,1,7,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,33.053194,12.052488,37.060445,3.533462,499.314038
std,NaN,NaN,NaN,0.992563,0.994216,1.010489,0.999278,79.314782
min,NaN,NaN,NaN,29.532429,8.508152,33.913847,0.269901,256.670582
25%,NaN,NaN,NaN,32.341822,11.388153,36.349257,2.930450,445.038277
50%,NaN,NaN,NaN,33.082008,11.983231,37.069367,3.533975,498.887875
75%,NaN,NaN,NaN,33.711985,12.753850,37.716432,4.126502,549.313828
max,NaN,NaN,NaN,36.139662,15.126994,40.005182,6.922689,765.518462

I am listening...
['Email', 'Address', 'Avatar', 'Avg. Session Length', 'Time on App', 'Time on Website', 'Length of Membership', 'Yearly Amount Spent']
I am listening...